### ISSUE TITLE
if type is password cannot use allowed pattern

### ISSUE THREAD

**Issue by TimWillis** [PolymerElements/iron-input#38]
The following only validates required, not the pattern.

                       <input  id="password" is="iron-input" type="password" name="password" required="true"
                               allowed-pattern="/^(?=.*[a-zA-Z0-9])(?=.*[_$@.])[a-zA-Z0-9_$@.]{6,20}$/">

**Comment by LM450N** [comment]
For now only the type __number__ is supported. To force to use the _allowed-pattern_ set the property _prevent-invalid-input_ as true.

**Comment by notwaldorf** [comment]
I think this has been fixed since the issue was opened. Here is a jsbin that uses `type="password"`, and prevents invalid input (like in the demo): http://jsbin.com/fekuxi/edit?html,output.

as @LM450N mentioned, the pattern is not used for validation -- it's just used to prevent other characters (see the docs: https://github.com/PolymerElements/iron-input/blob/master/iron-input.html#L71)

I think the "only the type="number" is supported" means that you can use `prevent-invalid-input` with just `type="number"`, and it will still work.
